VERSION 4.00
Begin VB.Form Form2 
   Caption         =   "Form2"
   ClientHeight    =   4230
   ClientLeft      =   1095
   ClientTop       =   1515
   ClientWidth     =   6720
   Height          =   4635
   Left            =   1035
   LinkTopic       =   "Form2"
   ScaleHeight     =   4230
   ScaleWidth      =   6720
   Top             =   1170
   Width           =   6840
End
Attribute VB_Name = "Form2"
Attribute VB_Creatable = False
Attribute VB_Exposed = False
